const { VITE_CRYPTO_STORAGE_KEY, VITE_API_URL, VITE_ADMIN_NAME, VITE_IMAGE_API_URL, VITE_VIEWPORTWIDTH }
    = import.meta.env

const API_URL = VITE_API_URL
const IMAGE_API_URL = VITE_IMAGE_API_URL
const ADMIN_NAME = VITE_ADMIN_NAME
const CRYPTO_STORAGE_KEY = VITE_CRYPTO_STORAGE_KEY
const VIEWPORTWIDTH = VITE_VIEWPORTWIDTH

export { API_URL, IMAGE_API_URL, ADMIN_NAME, CRYPTO_STORAGE_KEY, VIEWPORTWIDTH }
